import { SortData } from './sort';
export const FOOD: SortData[] = [
    { name: 'Turkey dinner', calories: '90', fat: '6', carbs: '4', protein: '9' },
    { name: 'Apple pie', calories: '67', fat: '21', carbs: '10', protein: '0.5' },
    { name: 'Almond', calories: '1', fat: '0.01', carbs: '1.61', protein: '21.22' },
    { name: 'Pumpkin pie', calories: '159', fat: '6', carbs: '24', protein: '6' },
    { name: 'Mash potatoes', calories: '214', fat: '7', carbs: '34', protein: '7' },
    { name: 'Sweet potatoes', calories: '119', fat: '0.1', carbs: '27', protein: '2.1' },
    { name: 'Cranberry sauce', calories: '159', fat: '6', carbs: '24', protein: '4' },
    { name: 'Walnut pie', calories: '23', fat: '52', carbs: '13.71', protein: '12' },
    { name: 'Blueberry Muffin', calories: '460', fat: '18', carbs: '69', protein: '6' },
    { name: 'Cherry pastry', calories: '460', fat: '22', carbs: '58', protein: '7' },
    { name: 'French Croissant', calories: '310', fat: '18', carbs: '32', protein: '6' },
    { name: 'Cinnamon roll', calories: '670', fat: '25', carbs: '100', protein: '13' },
    { name: 'Fudge Brownie', calories: '520', fat: '22', carbs: '80', protein: '6' },
    { name: 'Frozen yogurt', calories: '159', fat: '6', carbs: '24', protein: '4' },
    { name: 'Broccoli', calories: '50', fat: '0.1', carbs: '10', protein: '4.2' },
    { name: 'Potato', calories: '163', fat: '0.1', carbs: '37', protein: '4.3' },
    { name: 'Peanut', calories: '4', fat: '1', carbs: '1', protein: '38' },
    { name: 'Ice cream sandwich', calories: '237', fat: '9', carbs: '37', protein: '4' },
    { name: 'Eclair', calories: '262', fat: '16', carbs: '24', protein: '6' },
    { name: 'Cupcake', calories: '305', fat: '4', carbs: '67', protein: '4' },
    { name: 'Gingerbread', calories: '356', fat: '16', carbs: '49', protein: '4' },
];
